---
title: "Linear Models"
author: "Carson Barningham"
date: "2023-12-11"
output: pdf_document
---

```{r}
library(dplyr)
library(stats)

# Seed for reproducibility
set.seed(1)

# Read in data
data <- read.csv("CD8Tcell_screened1.csv")
names(data)[2] <- "condition"
train <- data[which(data$train == 1),]
test <- data[which(data$train == 0),]

# Get rid of train/test indicators in train and test sets
train <- select(train, -413)
test <- select(test, -413)
```

```{r}
# forward selection, takes about 3 minutes

linear_model = lm(condition~., data=train[,-1])
intercept_only = lm(condition ~ 1, data=train[,-1])
forward = step(intercept_only, direction='forward', scope = formula(linear_model), trace=0)
```

```{r}
# calculating test error and confusion matrix entries

yhat = predict(forward, test)
stim_stim = 0
stim_control = 0
control_control = 0
control_stim = 0
forward_test_err = 0
for (i in 1:length(yhat)) {
  if (test$condition[i] == -1) {
    if (yhat[i] >= 0) {
      forward_test_err = forward_test_err + 1
      control_stim = control_stim + 1
    } else {
      stim_stim = stim_stim + 1
    }
  } else {
    if (yhat[i] <= 0) {
      forward_test_err = forward_test_err + 1
      stim_control = stim_control + 1
    } else {
      control_control = control_control + 1
    }
  }
}
forward_test_err = forward_test_err / length(yhat)
forward_test_err

stim_stim
stim_control
control_control
control_stim
```

```{r}
length(forward$coefficients)

forward$coefficients
```

# ISG15, IF16, IFIT1, OAS1 are shared